#服务启动端口
server :  
  port :  8090

#数据库配置
spring:
    application:
        name: inventory-service
    datasource:
        name: test
        url: jdbc:mysql://18.188.53.2:3306/demo_schema?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
      host: 192.168.2.5
      #redis密码，没有密码的可以用～表示
      password: ~
      port: 6381
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
mybatis:
  type-aliases-package: com.tony.spring.boot.mapper
  mapper-locations: classpath:mapper/*.xml
  configLocation: classpath:mybatis-config.xml
  
endpoints:
  sensitive: false

eureka:
  client:
    instanceInfoReplicationIntervalSeconds: 60
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
# 日志输出
logging: 
    file: /boot.log
    level: 
        com.ibatis:ERROR
        root:ERROR
