server:
  port: 9000
spring:
  application:
    name: zuul-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    product-service:
      path: /**/product/**
    order-service:
      path: /**/order/**
    inventory-service:
      path: /**/inventory/**
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
   